import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { breakpoints, colorPrimitives, controlSize, motion, radius, semanticColors, spacing } from './tokens';

const meta = { title: 'Foundations/Design System', parameters: { layout: 'fullscreen' } } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;

const Page = ({ title, lead, children }: React.PropsWithChildren<{ title: string; lead: string }>) => (
  <main className="lo-foundation-page">
    <header style={{ display: 'grid', gap: 12 }}>
      <h1>{title}</h1>
      <p className="lo-foundation-lead">{lead}</p>
    </header>
    {children}
  </main>
);

const Swatch = ({ name, value }: { name: string; value: string }) => (
  <div className="lo-swatch">
    <div className="lo-swatch__color" style={{ '--swatch': value } as React.CSSProperties}/>
    <div className="lo-swatch__meta"><span className="lo-swatch__name">{name}</span><span className="lo-swatch__value">{value}</span></div>
  </div>
);

export const Overview: Story = { render: () => <Page title="Life OS Design System" lead="Warm, calm, natural and optimistic. The interface stays quiet so meaningful real-life moments can feel special."><section className="lo-demo-grid">{[['Calm','Warm neutrals, generous spacing and low visual noise.'],['Trustworthy','Semantic colors, predictable interaction and clear evidence.'],['Age-adaptive','Explorer, Builder and Parent densities share one component system.'],['Bidi-ready','Logical CSS properties and RTL review from day one.']].map(([a,b]) => <article className="lo-card-demo" key={a}><strong>{a}</strong><p style={{ color: 'var(--lo-text-secondary)', marginTop: 8 }}>{b}</p></article>)}</section></Page> };

export const ColorPrimitives: Story = { render: () => <Page title="Color primitives" lead="Raw palette values are foundation-only. Components consume semantic variables such as action.primary or money.save.">{Object.entries(colorPrimitives).map(([family, values]) => <section key={family}><h2 style={{ marginBottom: 12, textTransform: 'capitalize' }}>{family}</h2><div className="lo-swatch-grid">{Object.entries(values).map(([step, value]) => <Swatch key={step} name={`${family}.${step}`} value={value}/>)}</div></section>)}</Page> };

export const SemanticColor: Story = { render: () => <Page title="Semantic colors" lead="Color communicates UI meaning, never a child's moral worth."><div className="lo-swatch-grid"><Swatch name="background.page" value={semanticColors.background.page}/><Swatch name="background.surface" value={semanticColors.background.surface}/><Swatch name="action.primary" value={semanticColors.action.primary}/><Swatch name="money.give" value={semanticColors.money.give}/><Swatch name="money.save" value={semanticColors.money.save}/><Swatch name="money.spend" value={semanticColors.money.spend}/><Swatch name="progress.goal" value={semanticColors.progress.goal}/><Swatch name="progress.family" value={semanticColors.progress.family}/></div></Page> };

export const Typography: Story = { render: () => <Page title="Typography" lead="Inter for English and Noto Sans Arabic for Arabic. Arabic gets slightly more line-height rather than being forced into English metrics."><div className="lo-card-demo" style={{ display:'grid', gap:16 }}><div style={{ fontSize:32, fontWeight:600, lineHeight:1.2 }}>Display Large — 32 / 600</div><div style={{ fontSize:24, fontWeight:600 }}>Heading 1 — 24 / 600</div><div style={{ fontSize:17, fontWeight:600 }}>Heading 3 — 17 / 600</div><div style={{ fontSize:16 }}>Body Large — 16 / 400</div><div style={{ fontSize:14 }}>Body Medium — 14 / 400</div><div style={{ fontSize:12, fontWeight:600 }}>LABEL MEDIUM — 12 / 600</div></div><div className="lo-card-demo" dir="rtl" lang="ar"><div style={{ fontFamily:'var(--lo-font-arabic)', fontSize:26, fontWeight:600 }}>رحلتي ونموي اليوم</div><div style={{ fontFamily:'var(--lo-font-arabic)', fontSize:15, lineHeight:1.65, marginTop:12 }}>واجهة هادئة وواضحة تساعد الطفل على فهم ما يهم الآن بدون تحويل الحياة إلى لعبة نقاط.</div></div></Page> };

export const SpacingAndRadius: Story = { render: () => <Page title="Spacing & radius" lead="A 4px base grid supports compact parent UI and more spacious child experiences without inventing separate systems."><section className="lo-card-demo">{Object.entries(spacing).map(([k,v]) => <div key={k} style={{ display:'flex', alignItems:'center', gap:16, padding:'10px 0', borderBottom:'1px solid var(--lo-border-subtle)' }}><code style={{ width:90 }}>space.{k}</code><div style={{ width:Math.max(4,v), height:20, background:'var(--lo-sage-300)', borderRadius:8 }}/><span>{v}px</span></div>)}</section><section className="lo-demo-grid">{Object.entries(radius).map(([k,v]) => <div className="lo-card-demo" style={{ borderRadius:v }} key={k}>radius.{k} — {v}px</div>)}</section></Page> };

export const ElevationAndMotion: Story = { render: () => <Page title="Elevation & motion" lead="Most cards rely on borders and surface contrast. Stronger elevation and longer motion are reserved for overlays and meaningful milestones."><div className="lo-demo-grid">{[0,1,2,3].map(level => <div className="lo-card-demo" style={{ boxShadow:level===0?'none':`var(--lo-shadow-${level})` }} key={level}>Elevation {level}</div>)}</div><ul className="lo-rule-list"><li>Functional motion: {motion.duration.instant}–{motion.duration.normal}ms.</li><li>Feedback motion: about 300–700ms.</li><li>Milestone motion: {motion.duration.milestoneMin}–{motion.duration.milestoneMax}ms, always skippable.</li><li>Reduced-motion mode preserves meaning without spatial animation.</li></ul></Page> };

export const LayoutDensityAccessibility: Story = { render: () => <Page title="Layout, density & accessibility" lead="One component library adapts through experience-level sizing and density tokens."><section className="lo-card-demo"><h2>Reference widths</h2>{Object.entries(breakpoints).map(([k,v]) => <p key={k}><strong>{k}</strong>: {v}px</p>)}</section><section className="lo-demo-grid"><div className="lo-card-demo"><strong>Minimum</strong><p>{controlSize.minimum}px</p></div>{(['explorer','builder','parent'] as const).map(profile => <div className="lo-card-demo" key={profile}><strong style={{ textTransform:'capitalize' }}>{profile}</strong><p>Standard {controlSize[profile].standard}px<br/>Primary {controlSize[profile].primary}px</p></div>)}</section><ul className="lo-rule-list"><li>44px minimum interactive target; Explorer controls are larger.</li><li>Visible keyboard focus is mandatory.</li><li>Meaning must not depend on color alone.</li><li>Use logical CSS properties for RTL.</li></ul></Page> };

export const IconographyAndVisualWorld: Story = { render: () => <Page title="Iconography & Visual World" lead="Functional icons stay simple. The World carries the richer editorial/storybook illustration language."><ul className="lo-rule-list"><li><strong>Functional icons:</strong> outlined, 1.75–2px stroke, rounded caps and minimal detail.</li><li><strong>World:</strong> soft storybook/editorial, SVG-first, slightly isometric / 2.5D, natural daylight.</li><li><strong>Environment:</strong> sky #BFDCE7, water #6FA7AF, grass #90A979, forest #5F7657, sand #E2CE9E, stone #B9AF9A, wood #9B7154, clay #BB765D.</li><li><strong>Avoid:</strong> hyper-real 3D, neon game UI, loot-box aesthetics, heavy cartoon outlines.</li></ul></Page> };

export const ProductSemantics: Story = { render: () => <Page title="Product semantics" lead="Visual design must protect the frozen behavioral model rather than reintroducing a reward economy."><ul className="lo-rule-list"><li><strong>Responsibility completion:</strong> subtle success, never automatic money.</li><li><strong>Growth / learning:</strong> explicit progress and XP only where domain policy allows.</li><li><strong>Values and faith:</strong> story and meaning — no XP, money or morality score.</li><li><strong>Recovery:</strong> gentle recognition such as “You came back”, without bonus XP.</li><li><strong>Graduation:</strong> major emotional milestone because the system is no longer needed for that responsibility.</li><li><strong>Missing data:</strong> neutral uncertainty, never red failure.</li><li><strong>Family:</strong> shared world growth, never sibling ranking.</li><li><strong>Money:</strong> Give → Save → Spend; ordinary responsibilities never masquerade as paid Jobs.</li></ul></Page> };

export const VisualReferences: Story = { render: () => <Page title="V3.2 visual references" lead="These generated boards establish the visual mood only. Frozen System Design overrides any behavior shown in a concept image that conflicts with domain rules."><img className="lo-reference-board" src="/reference/concept-board-a.png" alt="Life OS concept board A"/><img className="lo-reference-board" src="/reference/concept-board-b.png" alt="Life OS concept board B"/><img className="lo-reference-board" src="/reference/concept-board-c.png" alt="Life OS concept board C"/></Page> };
